#!/bin/sh
# massages hevea output to make the lists look nice
# first, add the bullets per item
# then get rid of footer
# then get rid of the "References" heading
# then convert the umlauts to web-friendly format
# then make headings h3 instead of h1
# then get rid of the compact format so the bullet indent to the left
# then get rid of preamble
# then add the list tag
# then add end of list tag
cat $1 | \
sed 's/-thebibliography/-list/g' | \
sed 's/<\/\?DT[^>]*>//g' | \
sed 's/<\(\/\?\)DD\([^>]*\)>/<\1li\2>/g' | \
sed '/<!--HTMLFOOT-->/,$d' | \
sed 's/<\/BLOCKQUOTE><BR>/<\/BLOCKQUOTE>/' | \
sed 's/<\/BLOCKQUOTE>[.]<\/li>/<\/BLOCKQUOTE><\/li>/' | \
sed 's/<\/A>[.] <BLOCKQUOTE/<\/A><BLOCKQUOTE/' | \
sed 's/^<BR>//g' | \
sed 's/<H1 CLASS="chapter">\(<[^>]*>\)\?References<\/H1>//' | \
sed 's/\xfc/\&uuml;/' | \
sed 's/<H1/<H3/' | \
sed 's/<\/H1/<\/H3/' | \
sed 's/<DL CLASS="list" COMPACT="compact">//' | \
sed '1,/<BODY >/d' | \
sed 's/<!--SEC END -->/<ul>/' | \
sed 's/\(PDF\|PS\|HTML\)[.]/\1/' | \
sed 's/<\/DL>/<\/ul>/' >tmp && mv tmp $1
